<?php


function vineyard_sync_node_insert($node) {
  $sync = Vineyard_Sync::get_instance();

  if (isset($sync->nodes[$node->type]))
    $sync->send($node);
}

function vineyard_sync_node_update($node) {
  $sync = Vineyard_Sync::get_instance();

  if (isset($sync->nodes[$node->type]))
    $sync->send($node);
}

function vineyard_sync_node_delete($node) {
  print 'deleting';
  $sync = Vineyard_Sync::get_instance();

  if (isset($sync->nodes[$node->type]))
    $sync->send($node, true);
}